profile: tutorial
email: email@email.space
first_name: tutorial
last_name: tutorial
institution: dl
db_engine: postgresql_psycopg2
db_backend: core.psql_dos
db_host: localhost
db_name: aiida-mlip-tutorial
db_username: default
db_password: password
db_port: 5432
broker_protocol: amqp
broker_username: guest
broker_password: guest
broker_host: localhost
broker_port: 5672
broker_virtual_host: ""
repository: /home/tutorial
