name: "test"
E0s: 'average'
max_num_epochs: 1
model: 'MACE'
energy_key: 'qe_energy'
forces_key: 'qe_forces'
stress_key: 'qe_stress'
loss: 'universal'
energy_weight: 1
forces_weight: 10
stress_weight: 100
compute_stress: True
eval_interval: 2
error_table: 'PerAtomRMSE'
interaction_first: 'RealAgnosticResidualInteractionBlock'
interaction: 'RealAgnosticResidualInteractionBlock'
num_interactions: 2
correlation: 3
max_ell: 3
r_max: 4.0
max_L: 0
num_channels: 16
num_radial_basis: 6
MLP_irreps: '16x0e'
scaling: 'rms_forces_scaling'
lr: 0.005
weight_decay: 1e-8
ema: True
ema_decay: 0.995
scheduler_patience: 5
batch_size: 2
valid_batch_size: 2
patience: 50
amsgrad: True
device: 'cpu'
distributed: False
clip_grad: 100
keep_checkpoints: False
keep_isolated_atoms: True
save_cpu: True
