fmax: 0.01
pressure: 0.0
model: "https://github.com/stfc/janus-core/raw/main/tests/models/mace_mp_small.model"
arch: mace_mp
steps: 100
vectors-only: True
calc-kwargs:
    calc_kwargs:
      dispersion: True
      model: large
